<?php

namespace App\Http\Controllers\BackEnd;

use App\Http\Controllers\Controller;
use App\Http\Requests\BackEnd\Videos\Store;
use App\Models\Category;
use App\Models\Skill;
use App\Models\Tag;
use App\Models\Video;
use Illuminate\Http\Request;

class VideosController extends BackEndController
{
    public function __construct(Video $model)
    {
        parent::__construct($model);
    }

    protected function with()
    {
        return ['category','user']; // TODO: Change the autogenerated stub
    }

    protected function append()
    {
        $array= [
            'categories'=>Category::get(),
            'skills'=>Skill::get(),
            'tags'=>Tag::get(),
            'selectedSkills'=>[],
            'selectedTags'=>[],
        ];

        if (\request()->route()->parameter('video')) {
            $array['selectedSkills'] = $this->model->find(\request()->route()->parameter('video'))
                ->skills()->pluck('skills.id')->toArray();
        }
        if (\request()->route()->parameter('video')) {
            $array['selectedTags'] = $this->model->find(\request()->route()->parameter('video'))
                ->Tags()->pluck('Tags.id')->toArray();
        }
        return $array;
    }

    public function store(Store $request){

        $requestArray=$request->all()+['user_id'=> auth()->user()->id];
        $row = $this->model->create($requestArray);

        if(isset($requestArray['skill_id'])&&!empty($requestArray['skill_id'])) {
            $row->skills()->sync($requestArray['skill_id']);
        }
        if(isset($requestArray['tag_id'])&&!empty($requestArray['tag_id'])) {
            $row->tags()->sync($requestArray['tag_id']);
        }

        return redirect()->route('videos.index');
    }
    public function update($id,Store $request){

        $requestArray=$request->all();
        $row=$this->model->findOrFail($id);
        $row->update($requestArray);
        if(isset($requestArray['skills'])&&!empty($requestArray['skills'])) {
            $row->skills()->sync($requestArray['skills']);
        }
        if(isset($requestArray['tags'])&&!empty($requestArray['tags'])) {
            $row->tags()->sync($requestArray['tags']);
        }

        return redirect()->route('videos.index');
    }
}
